[project]
name = "text-to-speech"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "edge-tts>=7.0.2",
    "gradio>=5.35.0",
    "python-dotenv>=1.1.1",
    "rich>=14.0.0",
]
